### ISSUE TITLE
Line ending without separator throws index out of range

### ISSUE THREAD

**Issue by murilowlima** [bytefish/TinyCsvParser#7] opened 2016-01-06 12:12 UTC
Hello,

I'm working with lines that doesn't end with separator. Consider the following line:

01,B3215,ANA CLAUDIA,12

I'm tryng to map to a class with 4 fields, but the partser only works if I configure 3 fields. If i put the fourth field it throws and index ou of range exception.

**Comment by bytefish** [comment] 2016-01-06 12:39
Could you please add an example to reproduce the problematic behavior? :+1:

**Comment by murilowlima** [comment] 2016-01-06 13:00
Here is my code:

    //mapped class    
    public class MyClass
    {
        public string Property1 { get; set; }
        public string Property2 { get; set; }
        public string Property3 { get; set; }
        public string Property4 { get; set; }
    }

    //mapping class
    public class MyClassMapping : CsvMapping<MyClass>
    {
        public MyClassMapping()
        {
            MapProperty(1, x => x.Property1);
            MapProperty(2, x => x.Property2);
            MapProperty(3, x => x.Property3);
            MapProperty(4, x => x.Property4);
        }
    }

    //test code
    class Program
    {
        static void Main(string[] args)
        {
            CsvParserOptions csvParserOptions = new CsvParserOptions(skipHeader: false, fieldsSeparator: new[] { ',' });
            CsvParser<MyClass> csvParser = new CsvParser<MyClass>(csvParserOptions, new MyClassMapping());

            string line = "v01,v02,v03,v04";
            var mappedClass = csvParser.Parse(new string[] { line }).First();

            Console.WriteLine(string.Format("Is valid: {0}", mappedClass.IsValid));
            Console.WriteLine(string.Format("Error Column Index: {0}", mappedClass.Error.ColumnIndex));
            Console.WriteLine(string.Format("Error Value: {0}", mappedClass.Error.Value));
        }
    }



The code returns:

Is valid: false
Error Column Index: 4
Error Value: Column 4 Out of Range

I actually have 4 fields in the line. Shouldn't it return the four fields intead of error?

**Comment by bytefish** [comment] 2016-01-06 13:12
The Indices start with a zero. Please let me know, if the following mapping solves the problem:

```csharp
//mapping class
public class MyClassMapping : CsvMapping<MyClass>
{
    public MyClassMapping()
    {
        MapProperty(0, x => x.Property1);
        MapProperty(1, x => x.Property2);
        MapProperty(2, x => x.Property3);
        MapProperty(3, x => x.Property4);
    }
}
```

**Comment by bytefish** [comment] 2016-01-08 12:06
I could not reproduce the issue with the correct mapping. I am closing this bug as invalid. Please reopen the bug, if the problem persists.

**Closed by bytefish** 2016-01-08 12:06 UTC
Labels: invalid

**Comment by murilowlima** [comment] 2016-01-08 12:43
Ok. I corrected the mapping like you said and now it works. Thank you
